### ISSUE TITLE
MapboxDraw add

### ISSUE THREAD

**Issue by jparish3** [cityseer/vue-mapbox-map#1]
Added the following, but no result (or errors)
import MapboxDraw from '@mapbox/mapbox-gl-draw'

to props: // whether to instance draw
      draw: {
        type: Boolean,
        default: true
      }, 

 if (this.draw) {
        this.map.addControl(new MapboxDraw({
        displayControlsDefault: false,
         controls: {
         polygon: true,
         trash: true
        }
      }));
      }

**Comment by songololo** [comment]
do you possibly have a repo or minimal example I can look at?

**Comment by songololo** [comment]
@jparish3 Use the `@mapbox-ready` event to trigger a method once the map is ready, e.g.:

```
<vue-mapbox-map id='map-container'
:lng='location.lng'
:lat='location.lat'
@mapbox-ready='setMap'
></vue-mapbox-map>
```
Then set your `setMap` method to something like this:
```
setMap (map) {
  this.map = map
  this.draw = new MapboxDraw({
    displayControlsDefault: false
  })
  this.map.addControl(this.draw)
}
```
The map has to be instanced before you can add `MapboxDraw`.
